CREATE TABLE TEST_SCENARIOS (
    ID SERIAL PRIMARY KEY,
    CAMPAIGN_ID INT,
    TS_ID INT UNIQUE,
    TS_NAME CHAR(50),
    TS_STATUS CHAR(10) NOT NULL CHECK (TS_STATUS IN ('WAITING','POSITIVE','NEGATIVE','CANCELLED','SUSPENDED')),
    TS_TYPE VARCHAR(3) CHECK (TS_TYPE IN ('AUT','MAN'))
);

CREATE TABLE TEST_CASES (
    ID SERIAL PRIMARY KEY,
    TS_ID INT,
    TC_NAME VARCHAR(200),
    TC_CHECKBOX_ID INT UNIQUE NOT NULL,
    TC_CHECKBOX_STATUS BOOL NOT NULL DEFAULT FALSE,
    FOREIGN KEY (TS_ID)
        REFERENCES TEST_SCENARIOS (TS_ID)
);